INSERT INTO `roles` (`name`) VALUES ('ROLE_ADMIN');
INSERT INTO `roles` (`name`) VALUES ('ROLE_MODERATOR');
INSERT INTO `roles` (`name`) VALUES ('ROLE_USER');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('gkonopka','Grzegorz','Konopka','$2y$12$mWI3bRSpWyds3GkkTITmFuLCI7Eyiov7GON/9NTFkJxqQX4lWQgra','konopkagrzeg@gmail.com','1');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('moderator','Bill','Gates','$2y$12$YRNUnzw/yNuPaBYXP9m6VO48SuukLRkgobaHXL4j23Ey4/Xi9tv0W','billgates@hotmail.com','2');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('pstajniak','Piotr','Stajniak','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','pstajniak@outlook.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('czak','Cezary','Żak','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','cezaryzak@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('tnorek','Tadeusz','Norek','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','tadeusznorek@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mzakoscielny','Maciej','Zakościelny','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','mzakoscielny@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mstolc','Mateusz','Stolc','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','stolc@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('pkowal','Paulina','Kowal','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','pkowal@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('rkoni','Ryszard','Koni','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','konironi@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mczaplicki','Mariusz','Czaplicki','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','czapla@gmail.com','3');


INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Uriel Bowen','Litora Inc.','lorem.ut.aliquam@sem.com','netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus','true'),
('Garrison Pugh','Ut Sagittis Lobortis LLP','parturient@natoquepenatibus.edu','inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In','true'),('Tanek Dunlap','Ac Risus Morbi LLC','Phasellus.vitae.mauris@purus.co.uk','malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.','true'),
('Burton Best','Urna Incorporated','dolor.elit@estmauris.org','est, mollis non, cursus non, egestas a, dui. Cras pellentesque.','false'),
('Amena Wheeler','Neque Nullam Limited','risus.Quisque.libero@quamquis.edu','nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras','true'),
('Daryl Perry','Dui LLC','eros@Nunc.ca','a purus. Duis elementum, dui quis accumsan convallis, ante lectus','true'),
('Rhiannon Giles','Nisi LLC','Suspendisse.non@id.edu','enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum','false'),
('Kylynn Carson','Donec Est Nunc Inc.','Phasellus@mi.com','elit elit fermentum risus, at fringilla purus mauris a nunc.','true'),
('Azalia Cobb','Cursus Purus Corp.','facilisis@purusNullamscelerisque.com','mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras','true'),
('Amos Macias','Ante Nunc Mauris Inc.','lorem.vitae.odio@a.ca','Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Lyle Hancock','Luctus Sit Amet LLP','Integer@disparturientmontes.net','ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,','false'),
('James Hayes','Scelerisque Neque Sed Foundation','sodales.purus@cursusIntegermollis.ca','tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu','false'),
('Yuri Abbott','Aliquet Odio Inc.','aliquam.iaculis.lacus@loremvehicula.org','sit amet luctus vulputate, nisi sem semper erat, in consectetuer','true'),
('Rashad Buck','Ac Metus Vitae Ltd','sed.libero.Proin@atnisiCum.co.uk','Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet','false'),
('Jeremy Lyons','Et Magnis Dis LLP','Cum@dolor.com','Nunc ut erat. Sed nunc est, mollis non, cursus non,','false'),
('Shad Hernandez','At Associates','ut.odio.vel@Vivamusnonlorem.ca','Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.','true'),
('Reagan Good','Sociis Natoque Penatibus Foundation','adipiscing@ategestas.org','dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,','true'),
('Frances Dalton','Sed PC','neque@placeratCras.edu','Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis','true'),
('Adara Joyce','Nec Mauris Blandit Industries','erat.Vivamus.nisi@luctusvulputate.com','dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu','false'),
('Garth Chaney','Sit Company','ut@rutrummagnaCras.com','a neque. Nullam ut nisi a odio semper cursus. Integer','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Mufutau Barr','Nisi PC','Vestibulum.ante.ipsum@nec.org','purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla','false'),
('Hop Rich','Erat Etiam Vestibulum Inc.','Lorem.ipsum.dolor@utaliquam.ca','adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc','true'),('Chantale Franks','Semper Tellus Incorporated','habitant.morbi@urnaNunc.org','amet ornare lectus justo eu arcu. Morbi sit amet massa.','false'),('Paki Higgins','Libero Nec Ligula Associates','ante.dictum@semper.org','eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam','false'),('Bradley Frazier','Tortor Dictum Corp.','penatibus.et.magnis@Sedauctorodio.edu','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum','true'),('Bruno Winters','Parturient Montes Consulting','ac.facilisis@Maecenasornare.edu','ultrices a, auctor non, feugiat nec, diam. Duis mi enim,','false'),('Simon Ramirez','Quam Curabitur LLC','blandit.enim.consequat@feugiatplaceratvelit.ca','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.','true'),('Declan Bond','Posuere Cubilia Curae; Company','magna@Duis.net','feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam','false'),('Tucker Kerr','Nec Orci Inc.','orci.quis@netuset.ca','libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis','false'),('Charde Shepard','Ultrices Duis Volutpat Ltd','malesuada@luctus.ca','tristique senectus et netus et malesuada fames ac turpis egestas.','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Gloria Monroe','Nam Associates','Suspendisse.aliquet@Nuncpulvinararcu.net','aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend','true'),
('Brynn Stephenson','A Purus Duis Incorporated','tempor@ornarefacilisiseget.edu','faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend.','true'),
('Samson Cunningham','Pretium Neque LLC','ultrices.mauris.ipsum@Maecenas.co.uk','Aenean gravida nunc sed pede. Cum sociis natoque penatibus et','true'),
('Jordan Maddox','Libero Foundation','elementum.dui.quis@tristiqueaceleifend.co.uk','Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,','false'),
('Zia Hernandez','Erat Volutpat Nulla LLP','blandit.viverra@necmetus.edu','bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus','false'),
('Drake Hansen','Magna Lorem Inc.','aliquam.eu@erat.org','id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,','false'),
('Oleg Bradford','Quam Foundation','magna.a.neque@penatibus.co.uk','quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam','false'),
('Ebony Buckley','Diam At Inc.','egestas@Quisque.org','Praesent eu dui. Cum sociis natoque penatibus et magnis dis','true'),
('Ignacia Decker','Urna Vivamus Institute','eros@nonsollicitudin.edu','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,','true'),
('Finn Trujillo','Sem Mollis Dui LLP','ipsum.Donec.sollicitudin@aliquetliberoInteger.ca','id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Jason Gamble','Mauris Sagittis Placerat LLP','Nunc.sollicitudin.commodo@Maecenasornareegestas.edu','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','false'),
('Macaulay English','Orci Quis Lectus Corporation','tincidunt@convallisconvallisdolor.edu','lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus.','true'),
('Mollie Johnston','Semper LLP','enim.Etiam.gravida@malesuadaaugueut.com','orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec','true'),
('Demetria Mcknight','Eget Inc.','turpis@Nulla.edu','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.','true'),
('Blake Carson','At Fringilla Associates','augue.ut.lacus@pellentesquetellussem.co.uk','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,','true'),
('Steven Turner','Sem LLP','in.dolor.Fusce@ligulaconsectetuerrhoncus.edu','vitae erat vel pede blandit congue. In scelerisque scelerisque dui.','true'),
('Norman Gomez','Magna Sed LLC','felis@Duismi.co.uk','fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh','false'),
('Rose Holmes','Duis A Company','libero@per.net','tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim','false'),
('Gwendolyn Carver','Volutpat Nunc Sit Associates','Fusce@bibendumullamcorper.net','Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet','true'),
('Raymond Wilkinson','Sit Foundation','nunc@anteiaculis.edu','lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Ethan Farmer','Dui LLC','et@orciPhasellusdapibus.ca','arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim.','true'),
('Shaeleigh Carver','Purus Gravida PC','nulla@felisDonectempor.com','elit, a feugiat tellus lorem eu metus. In lorem. Donec','true'),
('Stuart Munoz','Interdum Curabitur Dictum Foundation','dis.parturient.montes@Nullamfeugiat.co.uk','Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus','false'),
('Shellie Finley','Et Ultrices Foundation','ipsum.Suspendisse@egestasascelerisque.org','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac','true'),
('Joel Knox','Lectus Convallis Est PC','massa@sagittislobortis.net','velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,','false'),
('Jacob Mcmahon','Vestibulum Lorem Sit Institute','mauris.erat@Donecfeugiat.co.uk','nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor','false'),
('Rooney Merrill','Consequat Corporation','nonummy.Fusce@estvitaesodales.co.uk','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,','false'),
('Mark Vaughn','Egestas Fusce Ltd','nec@Inmipede.org','dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque','true'),
('Noah Perez','Lacus Quisque Imperdiet LLC','hymenaeos.Mauris@rutrumurnanec.co.uk','elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum.','true'),
('Summer Holloway','Quis Corporation','Nulla.interdum.Curabitur@pedemalesuadavel.co.uk','neque sed dictum eleifend, nunc risus varius orci, in consequat','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Denton Hansen','Non Quam Pellentesque Limited','non.justo@ornareFusce.co.uk','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur','false'),
('Daniel Reese','Risus Institute','Quisque@pharetra.org','eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam','false'),
('Walker Calderon','Purus Gravida Company','pellentesque.tellus.sem@etlibero.edu','ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede','false'),
('Carla Trujillo','Morbi Sit Amet Associates','bibendum@sem.edu','enim, sit amet ornare lectus justo eu arcu. Morbi sit','true'),
('Amanda Livingston','Lectus Nullam Suscipit Incorporated','Duis@Inmi.ca','metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec','false'),
('Prescott Hale','Sed Nec Metus Company','Quisque.libero.lacus@ipsumDonec.com','at arcu. Vestibulum ante ipsum primis in faucibus orci luctus','false'),
('Elliott Durham','Dolor Associates','Donec@sagittisNullam.co.uk','dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est','true'),
('Dora Spence','Tempus Mauris Institute','ridiculus.mus.Aenean@quamCurabitur.com','molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl','false'),
('Asher Parks','Convallis Convallis Institute','dictum@rutrummagna.com','amet ante. Vivamus non lorem vitae odio sagittis semper. Nam','true'),
('Jesse Greene','Enim Condimentum Eget Incorporated','torquent.per@amet.org','posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet','true');

INSERT INTO `posts` (`heading`,`text`,`date`,`image`,`user_id`) VALUES ('sagittis. Duis gravida. Praesent','Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id,','2020-05-21T13:51:08-07:00',FILE_READ('http://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),2),
('Nullam feugiat placerat velit.','diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu','2020-10-11T07:40:36-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),3),
('et nunc.','Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu.','2019-12-25T10:36:06-08:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),3),
('in,','Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit','2020-06-16T16:37:21-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),1),
('vulputate dui,','Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare','2020-06-14T09:34:22-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),1),
('nulla.','in faucibus orci luctus et','2020-08-23T08:31:48-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),2),
('est ac mattis semper,','ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae,','2019-12-03T22:48:50-08:00',FILE_READ('http://github.com/konopkagrzegorz/training-blog-app/blob/master/src/main/resources/static/images/about_photo.jpg'),2),
('dui','at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis','2020-04-30T19:29:59-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),3),
('facilisis','arcu. Vivamus sit amet risus. Donec egestas.','2021-04-03T09:06:18-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),3),
('convallis','ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat','2021-06-12T20:52:06-07:00',FILE_READ('https://images.unsplash.com/photo-1513352098199-8ccf457b35a8?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=667&q=80'),2);
INSERT INTO `posts` (`heading`,`text`,`date`,`user_id`) VALUES ('egestas.','malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci','2020-03-21T14:49:50-07:00',3),
('egestas blandit. Nam nulla','felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.','2020-10-08T07:31:04-07:00',1),
('sapien. Cras dolor dolor,','Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet','2021-03-12T03:55:05-08:00',3),
('magna. Nam ligula','urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem','2021-10-22T16:44:31-07:00',1),
('natoque penatibus et magnis','vestibulum, neque sed dictum eleifend, nunc','2021-08-14T06:30:21-07:00',2),
('Nunc laoreet lectus quis massa.','vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt','2020-06-12T01:29:56-07:00',1),
('magna. Cras convallis','blandit mattis. Cras eget','2019-11-30T20:01:55-08:00',2),
('tempus eu, ligula.','vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,','2021-06-05T07:58:19-07:00',1),
('nulla. Donec non','bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean','2020-04-27T10:12:57-07:00',3),
('dui, nec tempus','molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc','2019-12-05T15:17:13-08:00',3);
INSERT INTO `posts` (`heading`,`text`,`date`,`user_id`) VALUES ('ante. Nunc mauris sapien, cursus','Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare','2020-04-27T18:16:28-07:00',3),
('molestie','dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas','2019-11-22T18:08:17-08:00',3),
('mi.','sodales','2021-01-04T07:26:08-08:00',2),
('Phasellus at augue','Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur','2020-07-30T05:18:57-07:00',2),
('in consequat enim diam vel','feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo','2020-01-03T09:41:01-08:00',3),
('lacinia vitae, sodales','placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.','2021-07-01T15:53:02-07:00',3),
('Phasellus dapibus quam quis','eget mollis lectus pede et risus. Quisque','2021-11-15T22:54:39-08:00',2),
('non, hendrerit','Phasellus elit pede, malesuada vel, venenatis','2021-04-23T19:12:45-07:00',3),
('dis parturient','ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla','2021-06-29T17:49:21-07:00',1),
('diam. Duis','consectetuer mauris id','2021-11-13T12:53:19-08:00',2);

INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus','2021-03-29T20:10:57-07:00',1,8),('diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.','2021-03-13T17:57:33-08:00',10,16),('nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod','2021-09-13T14:53:32-07:00',2,9),('massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient','2021-06-30T09:01:08-07:00',9,4),('iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed','2020-11-23T08:16:39-08:00',3,8),('orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.','2021-07-30T22:47:39-07:00',10,24),('consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam','2019-12-26T05:53:45-08:00',7,4),('odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor.','2020-04-23T20:48:50-07:00',4,20),('pellentesque, tellus sem mollis dui, in','2021-06-22T17:32:24-07:00',6,17),('imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat','2020-06-11T06:03:37-07:00',10,21);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor','2021-08-19T14:33:20-07:00',7,11),('porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et,','2021-02-18T10:15:17-08:00',7,18),('vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum','2021-02-15T05:58:17-08:00',9,24),('pede et risus. Quisque libero lacus, varius','2021-10-04T08:30:43-07:00',10,14),('eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim','2021-02-16T14:44:49-08:00',6,5),('neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.','2021-01-05T20:33:59-08:00',9,21),('sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida','2020-09-01T12:07:22-07:00',5,28),('magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus','2021-08-17T11:41:29-07:00',6,17),('tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et,','2020-05-05T20:40:08-07:00',2,14),('sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam','2021-02-09T02:31:11-08:00',5,4);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis','2020-01-02T16:46:34-08:00',3,8),('velit justo nec ante. Maecenas','2020-04-25T05:56:04-07:00',7,13),('Cras vehicula aliquet','2020-02-25T06:22:28-08:00',6,24),('Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla.','2020-11-01T01:22:05-07:00',4,25),('purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,','2020-12-17T00:45:48-08:00',10,17),('lectus convallis est, vitae sodales nisi magna sed','2020-04-21T01:44:57-07:00',3,15),('malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit','2020-07-25T16:27:31-07:00',1,26),('nec mauris blandit mattis. Cras eget','2020-12-24T09:25:10-08:00',4,28),('Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed','2020-11-01T01:32:40-07:00',9,7),('quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes,','2020-04-30T23:13:22-07:00',4,26);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus','2020-08-04T02:17:09-07:00',8,29),('Nam ligula elit, pretium','2020-01-03T03:57:24-08:00',7,25),('Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus','2020-01-26T10:14:54-08:00',6,14),('Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,','2020-10-21T03:01:58-07:00',8,29),('tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget','2019-12-15T04:29:35-08:00',2,14),('Aenean eget magna. Suspendisse tristique neque','2021-09-01T05:00:08-07:00',10,14),('Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse','2020-06-16T22:04:11-07:00',2,15),('malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed','2021-06-05T03:51:07-07:00',9,27),('ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent','2021-01-30T19:17:37-08:00',10,24),('varius et, euismod et, commodo at, libero. Morbi accumsan','2021-09-30T09:52:28-07:00',1,14);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris','2020-04-05T11:16:09-07:00',5,29),('lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat','2020-09-11T21:05:35-07:00',1,12),('urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque','2020-12-31T12:13:55-08:00',7,19),('Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien.','2021-10-26T23:59:44-07:00',1,21),('odio. Etiam ligula tortor, dictum eu, placerat eget,','2020-07-08T23:26:53-07:00',2,25),('nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec','2020-09-08T03:12:44-07:00',5,20),('imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium','2020-07-16T08:04:26-07:00',9,5),('non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id','2020-08-11T18:15:24-07:00',9,2),('Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,','2021-02-04T20:06:58-08:00',8,22),('est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet,','2020-08-03T18:19:41-07:00',8,13);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('dui, in sodales elit erat vitae risus. Duis a mi fringilla mi','2021-07-06T14:40:02-07:00',9,19),('augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget','2021-05-23T19:09:32-07:00',8,9),('urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis.','2021-03-14T15:23:28-07:00',1,12),('Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin','2020-04-02T20:07:56-07:00',7,15),('justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut','2019-12-31T00:29:07-08:00',7,1),('a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque','2021-08-15T04:42:44-07:00',1,4),('velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna','2020-03-13T07:37:52-07:00',4,11),('neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci,','2021-04-25T10:44:00-07:00',2,2),('non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat','2021-09-07T01:44:50-07:00',9,2),('velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis','2021-03-18T16:49:46-07:00',1,6);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin','2021-06-13T09:56:15-07:00',5,27),('vel, venenatis','2019-12-30T05:12:49-08:00',6,2),('Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo','2021-11-08T02:46:23-08:00',3,5),('parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus.','2020-10-03T16:56:18-07:00',10,7),('Nulla tincidunt, neque vitae semper','2020-09-13T04:15:44-07:00',10,13),('magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus','2021-11-21T06:43:35-08:00',7,13),('ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis','2020-01-17T10:38:01-08:00',3,5),('placerat, augue. Sed molestie. Sed id risus quis diam','2021-01-04T20:45:19-08:00',1,9),('egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed','2021-07-30T08:57:05-07:00',5,13),('urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce','2021-01-03T08:36:21-08:00',10,7);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit','2021-11-02T05:01:41-07:00',10,2),('Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien','2021-02-28T20:46:56-08:00',8,17),('lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac','2020-09-09T16:06:07-07:00',10,20),('nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed','2020-04-10T07:38:31-07:00',5,25),('ut, molestie in,','2021-08-12T22:55:30-07:00',8,5),('erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus','2020-07-05T23:17:55-07:00',4,15),('lacinia vitae, sodales at,','2020-03-09T00:49:43-07:00',10,9),('id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac','2019-12-13T16:58:14-08:00',4,16),('lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor','2020-12-10T02:17:57-08:00',8,4),('sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada','2021-08-19T14:22:27-07:00',7,28);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus','2021-04-02T11:45:52-07:00',2,1),('arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc','2020-02-24T07:01:00-08:00',9,15),('sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis','2021-10-12T07:47:08-07:00',6,22),('placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna','2020-12-22T06:49:00-08:00',3,19),('cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum','2021-02-01T02:28:11-08:00',9,22),('Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam,','2020-05-20T10:06:54-07:00',4,11),('Sed nunc est, mollis non,','2021-05-29T07:32:52-07:00',5,1),('massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum,','2020-11-28T08:58:20-08:00',4,28),('eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante.','2021-11-09T12:26:54-08:00',2,6),('Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis','2020-09-15T07:28:00-07:00',9,13);
INSERT INTO `comments` (`text`,`date`,`user_id`,`post_id`) VALUES ('fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit.','2020-09-18T00:27:12-07:00',9,28),('Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet','2019-12-17T02:05:12-08:00',1,6),('senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci.','2021-09-21T22:09:56-07:00',8,5),('ante. Vivamus non lorem vitae odio sagittis semper. Nam','2020-06-20T12:14:19-07:00',9,14),('urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam','2020-03-09T21:43:28-07:00',6,18),('dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu.','2021-07-03T23:06:24-07:00',5,14),('ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer','2021-07-31T11:37:39-07:00',2,24),('ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris','2021-02-27T08:53:22-08:00',2,1),('orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac','2020-09-29T02:16:38-07:00',7,7),('a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor','2020-09-20T06:59:27-07:00',4,27);

INSERT INTO `tags` (`name`) VALUES ('Others');
INSERT INTO `tags` (`name`) VALUES ('Fundamentals');
INSERT INTO `tags` (`name`) VALUES ('Powerlifting');
INSERT INTO `tags` (`name`) VALUES ('Weightlifting');
INSERT INTO `tags` (`name`) VALUES ('Football');
INSERT INTO `tags` (`name`) VALUES ('Basketball');
INSERT INTO `tags` (`name`) VALUES ('VoleyBall');
INSERT INTO `tags` (`name`) VALUES ('Running');
INSERT INTO `tags` (`name`) VALUES ('Sport Science');

INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (1,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (1,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (1,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (2,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (2,3);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (2,5);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (3,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (4,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (4,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (4,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (5,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (5,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (5,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (6,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (6,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (6,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (7,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (7,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (7,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (8,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (9,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (10,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (11,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (11,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (12,3);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (12,4);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (13,4);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (13,5);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (14,4);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (14,5);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (15,4);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (15,5);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (16,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (17,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (18,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (18,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (18,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (19,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (19,3);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (19,5);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (20,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (21,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (21,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (21,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (23,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (23,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (23,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (24,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (24,3);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (25,1);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (25,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (25,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (26,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (26,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (27,2);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (27,6);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (28,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (29,9);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (30,7);
INSERT INTO `posts_tags` (`post_id`, `tag_id`) VALUES (30,9);

-- CREATE TABLE `users`
-- (`id` INT(20) NOT NULL,
-- `username` VARCHAR(64) NOT NULL,
-- `first_name` VARCHAR(64) NOT NULL,
-- `last_name` VARCHAR(64) NOT NULL,
-- `password` VARCHAR(64) NOT NULL,
-- `email` VARCHAR(64) NOT NULL,
--   PRIMARY KEY (`id`)) engine=InnoDB;

--   CREATE TABLE `users` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `username` varchar(45) NOT NULL,
--   `first_name` varchar(64) NOT NULL,
--   `last_name` varchar(64) NOT NULL,
--   `password` varchar(64) NOT NULL,
--   `email` varchar(64) NOT NULL,
--   PRIMARY KEY (`id`)
-- );

-- CREATE TABLE `roles`
-- (`id` INT(20) NOT NULL AUTO_INCEREMENT,
-- `name` VARCHAR(64) NOT NULL,
--   PRIMARY KEY (`id`)) engine=InnoDB;
--
-- ALTER TABLE `roles` add constraint `users_fk_key` foreign key (`user_id`) references users (`id`);