INSERT INTO `roles` (`name`) VALUES ('ROLE_ADMIN');
INSERT INTO `roles` (`name`) VALUES ('ROLE_MODERATOR');
INSERT INTO `roles` (`name`) VALUES ('ROLE_USER');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('gkonopka','Grzegorz','Konopka','$2y$12$mWI3bRSpWyds3GkkTITmFuLCI7Eyiov7GON/9NTFkJxqQX4lWQgra','konopkagrzeg@gmail.com','1');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mkomenda','Martyna','Komenda','$2y$12$YRNUnzw/yNuPaBYXP9m6VO48SuukLRkgobaHXL4j23Ey4/Xi9tv0W','martyna.komenda7@gmail.com','2');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('rkonopka','Ryszard','Konopka','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','ryszardk@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('czak','Cezary','Żak','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','cezaryzak@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('tnorek','Tadeusz','Norek','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','tadeusznorek@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mzakoscielny','Maciej','Zakościelny','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','mzakoscielny@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mstolc','Mateusz','Stolc','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','stolc@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('pkowal','Paulina','Kowal','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','pkowal@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('rkonopka','Ryszard','Konopka','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','ryszardk@gmail.com','3');

INSERT INTO `users` (`username`, `first_name`, `last_name`, `password`, `email`, `role_id`)
VALUES ('mczaplicki','Mariusz','Czaplicki','$2y$12$pgO84pmff4nn0pRtw52sx.zei0UviGruBYJZ21Qq6JBogt83sZocK','czapla@gmail.com','3');


INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Uriel Bowen','Litora Inc.','lorem.ut.aliquam@sem.com','netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus','true'),('Garrison Pugh','Ut Sagittis Lobortis LLP','parturient@natoquepenatibus.edu','inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In','true'),('Tanek Dunlap','Ac Risus Morbi LLC','Phasellus.vitae.mauris@purus.co.uk','malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit.','true'),('Burton Best','Urna Incorporated','dolor.elit@estmauris.org','est, mollis non, cursus non, egestas a, dui. Cras pellentesque.','false'),('Amena Wheeler','Neque Nullam Limited','risus.Quisque.libero@quamquis.edu','nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras','true'),('Daryl Perry','Dui LLC','eros@Nunc.ca','a purus. Duis elementum, dui quis accumsan convallis, ante lectus','true'),('Rhiannon Giles','Nisi LLC','Suspendisse.non@id.edu','enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum','false'),('Kylynn Carson','Donec Est Nunc Inc.','Phasellus@mi.com','elit elit fermentum risus, at fringilla purus mauris a nunc.','true'),('Azalia Cobb','Cursus Purus Corp.','facilisis@purusNullamscelerisque.com','mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras','true'),('Amos Macias','Ante Nunc Mauris Inc.','lorem.vitae.odio@a.ca','Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Lyle Hancock','Luctus Sit Amet LLP','Integer@disparturientmontes.net','ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,','false'),('James Hayes','Scelerisque Neque Sed Foundation','sodales.purus@cursusIntegermollis.ca','tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu','false'),('Yuri Abbott','Aliquet Odio Inc.','aliquam.iaculis.lacus@loremvehicula.org','sit amet luctus vulputate, nisi sem semper erat, in consectetuer','true'),('Rashad Buck','Ac Metus Vitae Ltd','sed.libero.Proin@atnisiCum.co.uk','Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet','false'),('Jeremy Lyons','Et Magnis Dis LLP','Cum@dolor.com','Nunc ut erat. Sed nunc est, mollis non, cursus non,','false'),('Shad Hernandez','At Associates','ut.odio.vel@Vivamusnonlorem.ca','Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo.','true'),('Reagan Good','Sociis Natoque Penatibus Foundation','adipiscing@ategestas.org','dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel,','true'),('Frances Dalton','Sed PC','neque@placeratCras.edu','Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis','true'),('Adara Joyce','Nec Mauris Blandit Industries','erat.Vivamus.nisi@luctusvulputate.com','dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu','false'),('Garth Chaney','Sit Company','ut@rutrummagnaCras.com','a neque. Nullam ut nisi a odio semper cursus. Integer','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Mufutau Barr','Nisi PC','Vestibulum.ante.ipsum@nec.org','purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla','false'),('Hop Rich','Erat Etiam Vestibulum Inc.','Lorem.ipsum.dolor@utaliquam.ca','adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc','true'),('Chantale Franks','Semper Tellus Incorporated','habitant.morbi@urnaNunc.org','amet ornare lectus justo eu arcu. Morbi sit amet massa.','false'),('Paki Higgins','Libero Nec Ligula Associates','ante.dictum@semper.org','eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam','false'),('Bradley Frazier','Tortor Dictum Corp.','penatibus.et.magnis@Sedauctorodio.edu','Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum','true'),('Bruno Winters','Parturient Montes Consulting','ac.facilisis@Maecenasornare.edu','ultrices a, auctor non, feugiat nec, diam. Duis mi enim,','false'),('Simon Ramirez','Quam Curabitur LLC','blandit.enim.consequat@feugiatplaceratvelit.ca','lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque.','true'),('Declan Bond','Posuere Cubilia Curae; Company','magna@Duis.net','feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam','false'),('Tucker Kerr','Nec Orci Inc.','orci.quis@netuset.ca','libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis','false'),('Charde Shepard','Ultrices Duis Volutpat Ltd','malesuada@luctus.ca','tristique senectus et netus et malesuada fames ac turpis egestas.','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Gloria Monroe','Nam Associates','Suspendisse.aliquet@Nuncpulvinararcu.net','aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend','true'),('Brynn Stephenson','A Purus Duis Incorporated','tempor@ornarefacilisiseget.edu','faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend.','true'),('Samson Cunningham','Pretium Neque LLC','ultrices.mauris.ipsum@Maecenas.co.uk','Aenean gravida nunc sed pede. Cum sociis natoque penatibus et','true'),('Jordan Maddox','Libero Foundation','elementum.dui.quis@tristiqueaceleifend.co.uk','Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,','false'),('Zia Hernandez','Erat Volutpat Nulla LLP','blandit.viverra@necmetus.edu','bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus','false'),('Drake Hansen','Magna Lorem Inc.','aliquam.eu@erat.org','id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor,','false'),('Oleg Bradford','Quam Foundation','magna.a.neque@penatibus.co.uk','quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam','false'),('Ebony Buckley','Diam At Inc.','egestas@Quisque.org','Praesent eu dui. Cum sociis natoque penatibus et magnis dis','true'),('Ignacia Decker','Urna Vivamus Institute','eros@nonsollicitudin.edu','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,','true'),('Finn Trujillo','Sem Mollis Dui LLP','ipsum.Donec.sollicitudin@aliquetliberoInteger.ca','id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus','true');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Jason Gamble','Mauris Sagittis Placerat LLP','Nunc.sollicitudin.commodo@Maecenasornareegestas.edu','natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.','false'),('Macaulay English','Orci Quis Lectus Corporation','tincidunt@convallisconvallisdolor.edu','lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus.','true'),('Mollie Johnston','Semper LLP','enim.Etiam.gravida@malesuadaaugueut.com','orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec','true'),('Demetria Mcknight','Eget Inc.','turpis@Nulla.edu','urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim.','true'),('Blake Carson','At Fringilla Associates','augue.ut.lacus@pellentesquetellussem.co.uk','molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare,','true'),('Steven Turner','Sem LLP','in.dolor.Fusce@ligulaconsectetuerrhoncus.edu','vitae erat vel pede blandit congue. In scelerisque scelerisque dui.','true'),('Norman Gomez','Magna Sed LLC','felis@Duismi.co.uk','fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh','false'),('Rose Holmes','Duis A Company','libero@per.net','tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim','false'),('Gwendolyn Carver','Volutpat Nunc Sit Associates','Fusce@bibendumullamcorper.net','Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet','true'),('Raymond Wilkinson','Sit Foundation','nunc@anteiaculis.edu','lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Ethan Farmer','Dui LLC','et@orciPhasellusdapibus.ca','arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim.','true'),('Shaeleigh Carver','Purus Gravida PC','nulla@felisDonectempor.com','elit, a feugiat tellus lorem eu metus. In lorem. Donec','true'),('Stuart Munoz','Interdum Curabitur Dictum Foundation','dis.parturient.montes@Nullamfeugiat.co.uk','Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus','false'),('Shellie Finley','Et Ultrices Foundation','ipsum.Suspendisse@egestasascelerisque.org','pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac','true'),('Joel Knox','Lectus Convallis Est PC','massa@sagittislobortis.net','velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,','false'),('Jacob Mcmahon','Vestibulum Lorem Sit Institute','mauris.erat@Donecfeugiat.co.uk','nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor','false'),('Rooney Merrill','Consequat Corporation','nonummy.Fusce@estvitaesodales.co.uk','Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris,','false'),('Mark Vaughn','Egestas Fusce Ltd','nec@Inmipede.org','dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque','true'),('Noah Perez','Lacus Quisque Imperdiet LLC','hymenaeos.Mauris@rutrumurnanec.co.uk','elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum.','true'),('Summer Holloway','Quis Corporation','Nulla.interdum.Curabitur@pedemalesuadavel.co.uk','neque sed dictum eleifend, nunc risus varius orci, in consequat','false');
INSERT INTO `messages` (`name`,`subject`,`contact_email`,`text`,`status`) VALUES ('Denton Hansen','Non Quam Pellentesque Limited','non.justo@ornareFusce.co.uk','Cum sociis natoque penatibus et magnis dis parturient montes, nascetur','false'),('Daniel Reese','Risus Institute','Quisque@pharetra.org','eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam','false'),('Walker Calderon','Purus Gravida Company','pellentesque.tellus.sem@etlibero.edu','ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede','false'),('Carla Trujillo','Morbi Sit Amet Associates','bibendum@sem.edu','enim, sit amet ornare lectus justo eu arcu. Morbi sit','true'),('Amanda Livingston','Lectus Nullam Suscipit Incorporated','Duis@Inmi.ca','metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec','false'),('Prescott Hale','Sed Nec Metus Company','Quisque.libero.lacus@ipsumDonec.com','at arcu. Vestibulum ante ipsum primis in faucibus orci luctus','false'),('Elliott Durham','Dolor Associates','Donec@sagittisNullam.co.uk','dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est','true'),('Dora Spence','Tempus Mauris Institute','ridiculus.mus.Aenean@quamCurabitur.com','molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl','false'),('Asher Parks','Convallis Convallis Institute','dictum@rutrummagna.com','amet ante. Vivamus non lorem vitae odio sagittis semper. Nam','true'),('Jesse Greene','Enim Condimentum Eget Incorporated','torquent.per@amet.org','posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet','true');

-- CREATE TABLE `users`
-- (`id` INT(20) NOT NULL,
-- `username` VARCHAR(64) NOT NULL,
-- `first_name` VARCHAR(64) NOT NULL,
-- `last_name` VARCHAR(64) NOT NULL,
-- `password` VARCHAR(64) NOT NULL,
-- `email` VARCHAR(64) NOT NULL,
--   PRIMARY KEY (`id`)) engine=InnoDB;

--   CREATE TABLE `users` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `username` varchar(45) NOT NULL,
--   `first_name` varchar(64) NOT NULL,
--   `last_name` varchar(64) NOT NULL,
--   `password` varchar(64) NOT NULL,
--   `email` varchar(64) NOT NULL,
--   PRIMARY KEY (`id`)
-- );

-- CREATE TABLE `roles`
-- (`id` INT(20) NOT NULL AUTO_INCEREMENT,
-- `name` VARCHAR(64) NOT NULL,
--   PRIMARY KEY (`id`)) engine=InnoDB;
--
-- ALTER TABLE `roles` add constraint `users_fk_key` foreign key (`user_id`) references users (`id`);